### ISSUE TITLE
[JAX-RS] Fix issue with broken array output

### ISSUE THREAD

**Issue by who** [sudohippie/swagger-maven-plugin#1]
The `HTTP GET /pet/findByTags` route is yielding incorrect values for its schema.

Expected: `Array[string] (multi)` 
Actual `string`

Test failure: `com.github.kongchen.smp.integration.SwaggerMavenPluginTest.testGeneratedDoc`

**Comment by sudohippie** [comment]
I'm looking at this @hyeghiazaryan

**Comment by who** [comment]
Fixed
