### ISSUE TITLE
[Spring-MVC] Fix broken array output

### ISSUE THREAD

**Issue by who** [sudohippie/swagger-maven-plugin#2]
The `HTTP GET /pet/findByTags` route is yielding incorrect values for its schema.

Expected: `Array[string] (multi)`
Actual: `string`

Test failure: `com.github.kongchen.smp.integration.SpringMvcTest.testGeneratedDoc`

**Comment by hyeghiazaryan** [comment]
I'll work on this @who , @sudohippie

**Comment by who** [comment]
Fixed
